//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace сайт_магазина_СП.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klient()
        {
            this.zakazs = new HashSet<zakaz>();
        }
    
        public string ID_покупателя { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string номер_телефона { get; set; }
        public string электронная_почта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakazs { get; set; }
    }
}
