//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace сайт_магазина_СП.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class магазин_продуктов_пп03Entities1 : DbContext
    {
        public магазин_продуктов_пп03Entities1()
            : base("name=магазин_продуктов_пп03Entities1")
        {
        }
        private static магазин_продуктов_пп03Entities1 _context;
        public static магазин_продуктов_пп03Entities1 GetContext() 
        { 
            if (_context == null) 
            {
                _context = new магазин_продуктов_пп03Entities1(); 
            } return _context; 
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<info_company> info_company { get; set; }
        public virtual DbSet<klient> klients { get; set; }
        public virtual DbSet<product_types> product_types { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<zakaz> zakazs { get; set; }
        public virtual DbSet<пользователи> пользователи { get; set; }
    }
}
